### PR TITLE
Fix #2423 Region from coordinates does not work

### LINKED ISSUE #2423: Region from coordinates does not work - mapquestapi.com invalid AppKey
https://opencaching.pl/newcache.php
https://opencaching.pl/region.php?lat=54&lon=18&popup=y
https://www.mapquestapi.com/geocoding/v1/reverse?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&amp;location=54%2C18&amp;outFormat=json&amp;thumbMaps=false

```The AppKey submitted with this request is invalid.```

### PR DESCRIPTION
**Pull request by stefopl**
I reviewed free alternatives, but I didn’t find anything interesting.

* Nominatim 1 request/second
https://operations.osmfoundation.org/policies/nominatim/
https://nominatim.org/release-docs/3.6/api/Reverse/
https://nominatim.openstreetmap.org/reverse.php?lat=54&lon=18&zoom=6&format=jsonv2

* https://www.bigdatacloud.com/reverse-geocoding
Base Up to 50K queries /month FREE
Once you hit your monthly quota, the API will return errors until the start of the next month, unless you upgrade your package.

* https://developer.mapy.cz/en/rest-api-mapy-cz/function/geocoding/
250 000 credits free credits per month

* https://docs.locationiq.com/reference/reverse-api Free 5000 requests /day, 2 requests /second

I switched from MapQuest to Nominatim. It works fine for Poland, but I’m not sure about the rest. There are also other methods for determining the region, such as NUTS. NUTS doesn’t work locally for me.

### CODE REVIEW

File: src/Models/Coordinates/GeoCode.php [hunk 1]
```diff
@@ -188,6 +188,47 @@ public static function fromMapQuestApi(Coordinates $coords): ?GeoCode
...
+     */
+    public static function fromNominatimApi(Coordinates $coords): ?GeoCode
+    {
+        $lat = $coords->getLatitude();
+        $lon = $coords->getLongitude();
+        $url = "https://nominatim.openstreetmap.org/reverse?lat={$lat}&lon={$lon}&zoom=5&accept-language=*&format=jsonv2";
+
+        $context = stream_context_create([
+            'http' => [
+                'header' => "User-Agent: Opencaching\r\n"
```
Comment (deg-pl) [inline src/Models/Coordinates/GeoCode.php:204]: Can you change this code to per site solution? For example: Opencaching PL, Openaching NL etc.
